apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs-output
  template:
    metadata:
      labels:
        app: logs-output
    spec:
      containers:
        - name: logs-output
          image: logs-output:v1
          imagePullPolicy: IfNotPresent
