apiVersion: v1
kind: Service
metadata:
  name: logs-output
spec:
  type: ClusterIP
  selector:
    app: logs-output
  ports:
    - name: http
      port: 2345
      protocol: TCP
      targetPort: 3000
